name: "Tests e2e"
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        required: false
jobs:
  tests_e2e: 
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@4.1.1
        
      - name: Setup Node.js environment
        uses: actions/setup-node@4.0.0

      - name: Istall browsers
        run: npx playwright install --with-deps

      - name: Start tests
        run: npm run test
    
