name: "Tests e2e"
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        required: false
jobs:
  tests_e2e: 
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: install dependencies
      run: npm ci

    - name: Install browsers
      run: npx playwright install --with-deps

    - name: Start tests
      run: npm run test

    - name: upload pw-report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pw-report
        path: playwright-report

    - name: upload allure
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results
